interface SnowflakeConfig {
  accountName: string;
  region: string;
  cloudProvider: string;
  warehouseName: string;
  warehouseSize: string;
  databaseName: string;
  schemaName: string;
  roleName: string;
  userName: string;
  enableMultiCluster: boolean;
  autoSuspend: number;
  minClusters: number;
  maxClusters: number;
  enableDataSharing: boolean;
  enableTimeTravel: number;
  enableFailsafe: boolean;
  networkPolicy: string;
}

export function generateSnowflakeSetup(config: SnowflakeConfig): string {
  const {
    accountName,
    region,
    cloudProvider,
    warehouseName,
    warehouseSize,
    databaseName,
    schemaName,
    roleName,
    userName,
    enableMultiCluster,
    autoSuspend,
    minClusters,
    maxClusters,
    enableDataSharing,
    enableTimeTravel,
    enableFailsafe,
    networkPolicy
  } = config;

  const sections: string[] = [];

  sections.push(`-- ============================================================
-- Snowflake Data Warehouse Setup Script
-- Generated by CloudForge DevOps Platform
-- Account: ${accountName || '<YOUR_ACCOUNT>'}
-- Region: ${region} (${cloudProvider?.toUpperCase() || 'AWS'})
-- Generated: ${new Date().toISOString()}
-- ============================================================

-- IMPORTANT: Run this script with ACCOUNTADMIN or equivalent privileges
-- Make sure to review and modify any placeholder values before executing

USE ROLE ACCOUNTADMIN;
`);

  sections.push(`-- ============================================================
-- SECTION 1: Create Database and Schema
-- ============================================================

CREATE DATABASE IF NOT EXISTS ${databaseName || 'ANALYTICS_DB'}
  DATA_RETENTION_TIME_IN_DAYS = ${enableTimeTravel || 1}
  COMMENT = 'Main analytics database created by CloudForge';

USE DATABASE ${databaseName || 'ANALYTICS_DB'};

CREATE SCHEMA IF NOT EXISTS ${schemaName || 'PUBLIC'}
  DATA_RETENTION_TIME_IN_DAYS = ${enableTimeTravel || 1}
  COMMENT = 'Primary schema for ${databaseName || 'ANALYTICS_DB'}';

USE SCHEMA ${schemaName || 'PUBLIC'};
`);

  const warehouseOptions = [
    `WAREHOUSE_SIZE = '${warehouseSize || 'XSMALL'}'`,
    `AUTO_SUSPEND = ${autoSuspend || 300}`,
    `AUTO_RESUME = TRUE`,
    `INITIALLY_SUSPENDED = TRUE`
  ];

  if (enableMultiCluster) {
    warehouseOptions.push(`MIN_CLUSTER_COUNT = ${minClusters || 1}`);
    warehouseOptions.push(`MAX_CLUSTER_COUNT = ${maxClusters || 3}`);
    warehouseOptions.push(`SCALING_POLICY = 'STANDARD'`);
  }

  sections.push(`-- ============================================================
-- SECTION 2: Create Virtual Warehouse
-- ============================================================

CREATE WAREHOUSE IF NOT EXISTS ${warehouseName || 'COMPUTE_WH'}
  WITH
    ${warehouseOptions.join('\n    ')}
  COMMENT = 'Primary compute warehouse created by CloudForge';

-- Create additional warehouses for different workloads (optional)
CREATE WAREHOUSE IF NOT EXISTS ${warehouseName || 'COMPUTE_WH'}_ETL
  WITH
    WAREHOUSE_SIZE = 'MEDIUM'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
  COMMENT = 'ETL/ELT workload warehouse';

CREATE WAREHOUSE IF NOT EXISTS ${warehouseName || 'COMPUTE_WH'}_BI
  WITH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 600
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Business Intelligence reporting warehouse';
`);

  sections.push(`-- ============================================================
-- SECTION 3: Create Roles and Grant Privileges
-- ============================================================

-- Create functional roles
CREATE ROLE IF NOT EXISTS ${roleName || 'ANALYST_ROLE'}
  COMMENT = 'Role for data analysts';

CREATE ROLE IF NOT EXISTS ${roleName || 'ANALYST_ROLE'}_ADMIN
  COMMENT = 'Administrative role for ${roleName || 'ANALYST_ROLE'}';

CREATE ROLE IF NOT EXISTS DATA_ENGINEER_ROLE
  COMMENT = 'Role for data engineers';

CREATE ROLE IF NOT EXISTS DATA_SCIENTIST_ROLE
  COMMENT = 'Role for data scientists';

-- Create role hierarchy
GRANT ROLE ${roleName || 'ANALYST_ROLE'} TO ROLE ${roleName || 'ANALYST_ROLE'}_ADMIN;
GRANT ROLE DATA_ENGINEER_ROLE TO ROLE SYSADMIN;
GRANT ROLE DATA_SCIENTIST_ROLE TO ROLE SYSADMIN;
GRANT ROLE ${roleName || 'ANALYST_ROLE'}_ADMIN TO ROLE SYSADMIN;

-- Grant database privileges
GRANT USAGE ON DATABASE ${databaseName || 'ANALYTICS_DB'} TO ROLE ${roleName || 'ANALYST_ROLE'};
GRANT USAGE ON DATABASE ${databaseName || 'ANALYTICS_DB'} TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON DATABASE ${databaseName || 'ANALYTICS_DB'} TO ROLE DATA_SCIENTIST_ROLE;

-- Grant schema privileges
GRANT USAGE ON SCHEMA ${databaseName || 'ANALYTICS_DB'}.${schemaName || 'PUBLIC'} TO ROLE ${roleName || 'ANALYST_ROLE'};
GRANT USAGE ON SCHEMA ${databaseName || 'ANALYTICS_DB'}.${schemaName || 'PUBLIC'} TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON SCHEMA ${databaseName || 'ANALYTICS_DB'}.${schemaName || 'PUBLIC'} TO ROLE DATA_SCIENTIST_ROLE;

-- Grant table privileges (for future tables)
GRANT SELECT ON FUTURE TABLES IN SCHEMA ${databaseName || 'ANALYTICS_DB'}.${schemaName || 'PUBLIC'} TO ROLE ${roleName || 'ANALYST_ROLE'};
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA ${databaseName || 'ANALYTICS_DB'}.${schemaName || 'PUBLIC'} TO ROLE DATA_ENGINEER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ${databaseName || 'ANALYTICS_DB'}.${schemaName || 'PUBLIC'} TO ROLE DATA_SCIENTIST_ROLE;

-- Grant warehouse privileges
GRANT USAGE ON WAREHOUSE ${warehouseName || 'COMPUTE_WH'} TO ROLE ${roleName || 'ANALYST_ROLE'};
GRANT USAGE ON WAREHOUSE ${warehouseName || 'COMPUTE_WH'}_BI TO ROLE ${roleName || 'ANALYST_ROLE'};
GRANT USAGE ON WAREHOUSE ${warehouseName || 'COMPUTE_WH'}_ETL TO ROLE DATA_ENGINEER_ROLE;
GRANT USAGE ON WAREHOUSE ${warehouseName || 'COMPUTE_WH'} TO ROLE DATA_SCIENTIST_ROLE;
`);

  if (userName) {
    sections.push(`-- ============================================================
-- SECTION 4: Create Users
-- ============================================================

-- Create admin user
-- IMPORTANT: Change the password before running in production!
CREATE USER IF NOT EXISTS ${userName}
  PASSWORD = 'CHANGE_ME_IMMEDIATELY!'
  DEFAULT_ROLE = ${roleName || 'ANALYST_ROLE'}_ADMIN
  DEFAULT_WAREHOUSE = ${warehouseName || 'COMPUTE_WH'}
  DEFAULT_NAMESPACE = ${databaseName || 'ANALYTICS_DB'}.${schemaName || 'PUBLIC'}
  MUST_CHANGE_PASSWORD = TRUE
  COMMENT = 'Admin user created by CloudForge';

-- Grant role to user
GRANT ROLE ${roleName || 'ANALYST_ROLE'}_ADMIN TO USER ${userName};

-- Sample user creation template for team members
-- CREATE USER IF NOT EXISTS <username>
--   PASSWORD = '<temporary_password>'
--   DEFAULT_ROLE = ${roleName || 'ANALYST_ROLE'}
--   DEFAULT_WAREHOUSE = ${warehouseName || 'COMPUTE_WH'}
--   MUST_CHANGE_PASSWORD = TRUE;
-- GRANT ROLE ${roleName || 'ANALYST_ROLE'} TO USER <username>;
`);
  }

  if (networkPolicy) {
    sections.push(`-- ============================================================
-- SECTION 5: Network Security Policy
-- ============================================================

-- Create network policy to restrict access
-- IMPORTANT: Update the allowed IP list before enabling!
CREATE NETWORK POLICY IF NOT EXISTS ${networkPolicy}
  ALLOWED_IP_LIST = ('0.0.0.0/0')  -- CHANGE THIS TO YOUR CORPORATE IP RANGE
  BLOCKED_IP_LIST = ()
  COMMENT = 'Network policy created by CloudForge';

-- To apply network policy to account (requires ACCOUNTADMIN):
-- ALTER ACCOUNT SET NETWORK_POLICY = ${networkPolicy};

-- To apply network policy to specific user:
-- ALTER USER ${userName || '<username>'} SET NETWORK_POLICY = ${networkPolicy};
`);
  }

  if (enableDataSharing) {
    sections.push(`-- ============================================================
-- SECTION 6: Secure Data Sharing Setup
-- ============================================================

-- Create a share for external data sharing
CREATE SHARE IF NOT EXISTS ${databaseName || 'ANALYTICS_DB'}_SHARE
  COMMENT = 'Secure data share created by CloudForge';

-- Grant privileges to share
GRANT USAGE ON DATABASE ${databaseName || 'ANALYTICS_DB'} TO SHARE ${databaseName || 'ANALYTICS_DB'}_SHARE;
GRANT USAGE ON SCHEMA ${databaseName || 'ANALYTICS_DB'}.${schemaName || 'PUBLIC'} TO SHARE ${databaseName || 'ANALYTICS_DB'}_SHARE;

-- To add tables to share:
-- GRANT SELECT ON TABLE ${databaseName || 'ANALYTICS_DB'}.${schemaName || 'PUBLIC'}.<table_name> TO SHARE ${databaseName || 'ANALYTICS_DB'}_SHARE;

-- To add consumer accounts:
-- ALTER SHARE ${databaseName || 'ANALYTICS_DB'}_SHARE ADD ACCOUNTS = <consumer_account>;
`);
  }

  sections.push(`-- ============================================================
-- SECTION 7: Resource Monitors (Cost Control)
-- ============================================================

-- Create resource monitor to control costs
CREATE RESOURCE MONITOR IF NOT EXISTS ${warehouseName || 'COMPUTE_WH'}_MONITOR
  WITH
    CREDIT_QUOTA = 100
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
      ON 75 PERCENT DO NOTIFY
      ON 90 PERCENT DO NOTIFY
      ON 100 PERCENT DO SUSPEND
  COMMENT = 'Resource monitor for ${warehouseName || 'COMPUTE_WH'}';

-- Apply resource monitor to warehouse
ALTER WAREHOUSE ${warehouseName || 'COMPUTE_WH'} SET RESOURCE_MONITOR = ${warehouseName || 'COMPUTE_WH'}_MONITOR;

-- Create account-level resource monitor (optional, requires ACCOUNTADMIN)
-- CREATE RESOURCE MONITOR IF NOT EXISTS ACCOUNT_MONITOR
--   WITH CREDIT_QUOTA = 1000
--   FREQUENCY = MONTHLY
--   TRIGGERS
--     ON 50 PERCENT DO NOTIFY
--     ON 75 PERCENT DO NOTIFY
--     ON 100 PERCENT DO SUSPEND_IMMEDIATE;
`);

  sections.push(`-- ============================================================
-- SECTION 8: Sample Staging Tables and File Formats
-- ============================================================

-- Create file formats for data loading
CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE
  COMPRESSION = AUTO;

CREATE FILE FORMAT IF NOT EXISTS JSON_FORMAT
  TYPE = JSON
  COMPRESSION = AUTO
  STRIP_OUTER_ARRAY = TRUE;

CREATE FILE FORMAT IF NOT EXISTS PARQUET_FORMAT
  TYPE = PARQUET
  COMPRESSION = SNAPPY;

-- Create internal stage for file uploads
CREATE STAGE IF NOT EXISTS ${databaseName || 'ANALYTICS_DB'}_STAGE
  FILE_FORMAT = CSV_FORMAT
  COMMENT = 'Internal stage for data loading';

-- Sample external stage template (S3)
-- CREATE STAGE IF NOT EXISTS ${databaseName || 'ANALYTICS_DB'}_S3_STAGE
--   URL = 's3://your-bucket-name/path/'
--   STORAGE_INTEGRATION = <your_storage_integration>
--   FILE_FORMAT = PARQUET_FORMAT;
`);

  sections.push(`-- ============================================================
-- SECTION 9: Sample Dimensional Model (Star Schema)
-- ============================================================

-- Date dimension table
CREATE TABLE IF NOT EXISTS DIM_DATE (
  DATE_KEY INTEGER PRIMARY KEY,
  FULL_DATE DATE NOT NULL,
  DAY_OF_WEEK INTEGER,
  DAY_NAME VARCHAR(10),
  DAY_OF_MONTH INTEGER,
  DAY_OF_YEAR INTEGER,
  WEEK_OF_YEAR INTEGER,
  MONTH_NUMBER INTEGER,
  MONTH_NAME VARCHAR(10),
  QUARTER INTEGER,
  YEAR INTEGER,
  IS_WEEKEND BOOLEAN,
  IS_HOLIDAY BOOLEAN
);

-- Sample fact table template
-- CREATE TABLE IF NOT EXISTS FACT_SALES (
--   SALE_ID INTEGER AUTOINCREMENT PRIMARY KEY,
--   DATE_KEY INTEGER REFERENCES DIM_DATE(DATE_KEY),
--   PRODUCT_KEY INTEGER,
--   CUSTOMER_KEY INTEGER,
--   QUANTITY INTEGER,
--   UNIT_PRICE DECIMAL(10,2),
--   TOTAL_AMOUNT DECIMAL(12,2),
--   CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
-- );
`);

  sections.push(`-- ============================================================
-- SECTION 10: Useful Queries and Commands
-- ============================================================

-- View warehouse usage
-- SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
-- WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
-- ORDER BY START_TIME DESC;

-- View query history
-- SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
-- WHERE START_TIME >= DATEADD(DAY, -1, CURRENT_TIMESTAMP())
-- ORDER BY START_TIME DESC
-- LIMIT 100;

-- View storage usage
-- SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE
-- ORDER BY USAGE_DATE DESC
-- LIMIT 30;

-- View login history
-- SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY
-- WHERE EVENT_TIMESTAMP >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
-- ORDER BY EVENT_TIMESTAMP DESC;

-- ============================================================
-- Setup Complete!
-- ============================================================
-- Next Steps:
-- 1. Change default passwords for any created users
-- 2. Update network policy with your corporate IP ranges
-- 3. Create additional schemas as needed
-- 4. Set up storage integrations for external stages
-- 5. Configure BI tool connections
-- ============================================================
`);

  return sections.join('\n');
}
